apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: bugzooka
  namespace: bugzooka
  labels:
    app: bugzooka
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: ${BUGZOOKA_IMAGE}
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
