apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: bugzooka
spec:
  template:
    spec:
      initContainers:
        - name: rag
          image: ${RAG_IMAGE}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Copying RAG data to shared volume...";
              cp -r /rag/vector_db/* /shared-rag/;
              echo "Done copying RAG data.";
          envFrom:
            - secretRef:
                name: bugzooka-env
          volumeMounts:
            - name: rag-db
              mountPath: /shared-rag
      containers:
        - name: bugzooka
          env:
            - name: PRODUCT
              value: "openshift"
            - name: CI
              value: "prow"
          volumeMounts:
            - name: rag-db
              mountPath: /rag
      volumes:
        - name: rag-db
          emptyDir: {}
