apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: bugzooka
spec:
  template:
    spec:
      containers:
        - name: bugzooka
          volumeMounts:
            - name: rag-db
              mountPath: /rag
        - name: rag
          image: ${RAG_IMAGE}
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: bugzooka-env
          volumeMounts:
            - name: rag-db
              mountPath: /rag
      volumes:
        - name: rag-db
          emptyDir: {}
